<template><div><h2 id="컴포넌트-사용-예제" tabindex="-1"><a class="header-anchor" href="#컴포넌트-사용-예제" aria-hidden="true">#</a> 컴포넌트 사용 예제</h2>
<h3 id="컴포넌트-마운트" tabindex="-1"><a class="header-anchor" href="#컴포넌트-마운트" aria-hidden="true">#</a> 컴포넌트 마운트</h3>
<p>@[code](@/docs/src/vue2-component/vue2-component.html</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h3 id="buttoncomponent" tabindex="-1"><a class="header-anchor" href="#buttoncomponent" aria-hidden="true">#</a> ButtonComponent</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h3 id="countercomponent" tabindex="-1"><a class="header-anchor" href="#countercomponent" aria-hidden="true">#</a> CounterComponent</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h3 id="reactivecomponent" tabindex="-1"><a class="header-anchor" href="#reactivecomponent" aria-hidden="true">#</a> ReactiveComponent</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="nowcomponent" tabindex="-1"><a class="header-anchor" href="#nowcomponent" aria-hidden="true">#</a> NowComponent</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="nowcontrollercomponent" tabindex="-1"><a class="header-anchor" href="#nowcontrollercomponent" aria-hidden="true">#</a> NowControllerComponent</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="parentcomponent" tabindex="-1"><a class="header-anchor" href="#parentcomponent" aria-hidden="true">#</a> ParentComponent</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="childcomponent" tabindex="-1"><a class="header-anchor" href="#childcomponent" aria-hidden="true">#</a> ChildComponent</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h2 id="컴포넌트-코어" tabindex="-1"><a class="header-anchor" href="#컴포넌트-코어" aria-hidden="true">#</a> 컴포넌트 코어</h2>
<h4 id="fp-js" tabindex="-1"><a class="header-anchor" href="#fp-js" aria-hidden="true">#</a> fp.js</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="store-js" tabindex="-1"><a class="header-anchor" href="#store-js" aria-hidden="true">#</a> store.js</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="helper-js" tabindex="-1"><a class="header-anchor" href="#helper-js" aria-hidden="true">#</a> helper.js</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div><h4 id="component-js" tabindex="-1"><a class="header-anchor" href="#component-js" aria-hidden="true">#</a> component.js</h4>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>File not found</code></pre><div class="line-numbers" aria-hidden="true"></div></div></div></template>


