// Generated by dts-bundle-generator v8.0.1

export interface CommonProps {
	description: string;
}
export type CommonName = string;
export interface Props extends CommonProps {
	url: string;
	name: CommonName;
}

export {};
